name: CI Build (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build project
      - name: Build project
        run: dotnet build --no-restore
